#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mtr
Version  : 0.92
Release  : 2
URL      : https://github.com/traviscross/mtr/archive/v0.92.tar.gz
Source0  : https://github.com/traviscross/mtr/archive/v0.92.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: mtr-bin
Requires: mtr-data
Requires: mtr-license
Requires: mtr-man
BuildRequires : gtk+-dev
BuildRequires : libcap-dev
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)

%description
WHAT IS MTR?
mtr combines the functionality of the 'traceroute' and 'ping' programs
in a single network diagnostic tool.

%package bin
Summary: bin components for the mtr package.
Group: Binaries
Requires: mtr-data
Requires: mtr-license
Requires: mtr-man

%description bin
bin components for the mtr package.


%package data
Summary: data components for the mtr package.
Group: Data

%description data
data components for the mtr package.


%package license
Summary: license components for the mtr package.
Group: Default

%description license
license components for the mtr package.


%package man
Summary: man components for the mtr package.
Group: Default

%description man
man components for the mtr package.


%prep
%setup -q -n mtr-0.92

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534571194
%reconfigure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1534571194
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/mtr
cp COPYING %{buildroot}/usr/share/doc/mtr/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mtr
/usr/bin/mtr-packet

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/mtr

%files license
%defattr(-,root,root,-)
/usr/share/doc/mtr/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/mtr-packet.8
/usr/share/man/man8/mtr.8
